version: "3.9"
services:

  mysqldb:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3310:3306

  gestionski:
    build:
      context: ./
    image: lourasjihed/alpine:1.0.0
    ports:
      - 8089:8089

  front-ski:
    build:
      context: ./front-ski
    image: "gestion_skier_image_frontend"
    ports:
       - "4200:4200"
      


