version: "2.32.4"
services:

  mysqldb:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3307:3306

  GestionSki:
    build:
      context: ./
    image: "gestion_skier_image"
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
