services:
  mysqldb:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  gestionski:
    image: "eyanehdi-groupe2-gestion-station-ski:1.0"
    container_name: gestionski
    ports:
      - "8089:8089"
    volumes:
      - ./logs:/logs
    environment:
      - "spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640"
    depends_on:
      - mysqldb
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/touta/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - gestionski
