version: "2.32.4"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
        - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb" ]
      interval: 10s
      timeout: 5s
      retries: 5


  gestionski:
    image: gestion-station-ski:1.0
    ports:
      - 8089:8089
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    links:
      - mysqldb
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: host
