version: "2.32.4"
services:
  mysqldb:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  gestionski:
    image: "gestion-station-ski:1.0"
    ports:
      - "8089:8089"
    volumes:
      - ./logs:/logs
    environment:
      - "spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640"
    depends_on:
      - mysqldb
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
        - "3000:3000"
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
        - prometheus
