version: "3.9"
services:

  mysqldb:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3310:3306

  gestionski:
    build:
      context: ./
    image: lourasjihed/alpine:1.0.0
    ports:
      - 8089:8089

  frontski:
    build:
      context: ./front-ski
    image: "gestion_skier_image_frontend"
    ports:
       - "4200:4200"
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - /home/vagrant/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      depends_on:
        - gestionski
      


