version: "2.32.4"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped


  gestionski:
    image: gestion-station-ski:1.0
    container_name: gestionski
    ports:
      - 8089:8089
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    depends_on:
      - mysqldb


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/vagrant/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - gestionski