global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gestionski'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gestionski:8089']


  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['172.25.251.16:8080']
